- name: Initial Setup
  hosts: all
  become: yes
  tasks:
    - name: Create ansible User
      user:
        name: ansible
        state: present
    - name: Add ansible to sudoers
      lineinfile:
        path: /etc/sudoers.d/ansible
        line: "ansible        ALL=(ALL)       NOPASSWD: ALL"
        state: present
        create: true
    - name: Add ssh key
      ansible.posix.authorized_key:
        user: ansible
        state: present 
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
